### PR TITLE
Test with very large grammar. Possibly causing problems

### PR DESCRIPTION
**Pull request by IzakMarais**
In response to https://github.com/katydid/katydid/pull/3#issuecomment-305984160. 

Not sure if I did everything correctly. After generating the tests and running against the latest katydid,  I get:

    $ make test
    go test ./...
    [...]
    ok      github.com/katydid/katydid/relapse/ast  0.030s
        --- FAIL: TestSuite (6.92s)
            --- FAIL: TestSuite/BananaLargeMatchPbnum (0.11s)
                suite_test.go:58: a state explosion has occured
    FAIL

### CODE REVIEW

**Comment by awalterschulze** [comment]
I guess that happens in the auto package.
Since the auto package tries to compile everything.
We should manually skip this test in the auto package, like its done for the GoBigOrGoHome test.
https://github.com/katydid/katydid/blob/master/relapse/auto/suite_test.go#L47-L49

**Comment by IzakMarais** [comment]
OK, should I add a similar condition for this test name to the katydid repo? Or rename my test to start with GoBigOr (only affecting the testsuite repo)?

**Comment by awalterschulze** [comment]
I'll make a quick change to main repo.

**Comment by IzakMarais** [comment]
Cool, thanks.

**Comment by awalterschulze** [comment]
done

**Comment by awalterschulze** [comment]
Thank you very much :)

**Pull request merged**
